require 'json'

package = JSON.parse(File.read(File.join(__dir__, '..', 'package.json')))

Pod::Spec.new do |s|
  s.name           = 'ExpoNearbyConnections'
  s.version        = package['version']
  s.summary        = package['description']
  s.description    = package['description']
  s.license        = package['license']
  s.author         = package['author']
  s.homepage       = package['homepage']
  s.platforms      = { :ios => '15.1' }
  s.swift_version  = '5.9'
  s.source         = { git: 'https://github.com/puguhsudarma/expo-nearby-connections' }

  s.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES',
    'SWIFT_COMPILATION_MODE' => 'wholemodule'
  }

  s.source_files = "**/*.{h,m,swift}"

  # Add all files generated by Nitrogen (NitroModules dependency + generated specs)
  load File.join(__dir__, '..', 'nitrogen', 'generated', 'ios', 'ExpoNearbyConnections+autolinking.rb')
  add_nitrogen_files(s)
end
